# This workflow will generate a release distribution and upload it to PyPI

name: Create and Publish Release
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Version
        run: |
          export VERSION=$(python setup.py --version)
      - uses: ncipollo/release-action@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{VERSION}}
